Use the correct libvirt pool instead of hardcoded default
We always used the "default"

    $ image-builder upload -to libvirt --libvirt-pool images ...
    ...
    error: Failed to find storage pool: virError(Code=49, Domain=18, Message='Storage pool not found: no storage pool with matching name 'default'')